server:
  port: ${SERVER.PORT:8080}

spring:
  application:
    name: super-killer-backend
  mail:
    host: ${MAIL.HOST:}
    port: ${MAIL.PORT:587}
    username: ${MAIL.USERNAME:}
    password: ${MAIL.PASSWORD:}
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://${DB.HOST:127.0.0.1}:${DB.PORT:23306}/SuperKillerAdmin?useUnicode=true&characterEncoding=utf-8&useSSL=false&serverTimezone=Asia/Shanghai
    username: ${DB.USERNAME:xwu36}
    password: ${DB.PASSWORD:Wu121380..}
    hikari:
      pool-name: ${DB.POOL.NAME:sak-hikari-aliyun}
      minimum-idle: ${DB.POOL.MIN_IDLE:5}
      maximum-pool-size: ${DB.POOL.MAX_SIZE:20}
      idle-timeout: ${DB.POOL.IDLE_TIMEOUT:600000}
      max-lifetime: ${DB.POOL.MAX_LIFETIME:1800000}
      connection-timeout: ${DB.POOL.CONNECTION_TIMEOUT:30000}
      validation-timeout: ${DB.POOL.VALIDATION_TIMEOUT:5000}
      keepalive-time: ${DB.POOL.KEEPALIVE_TIME:300000}
  data:
    redis:
      host: ${REDIS.HOST:127.0.0.1}
      port: ${REDIS.PORT:26379}
      password:
      database: 1
      timeout: ${REDIS.TIMEOUT:5s}
      connect-timeout: ${REDIS.CONNECT_TIMEOUT:10s}
      lettuce:
        pool:
          enabled: true
          max-active: ${REDIS.POOL.MAX_ACTIVE:16}
          max-idle: ${REDIS.POOL.MAX_IDLE:8}
          min-idle: ${REDIS.POOL.MIN_IDLE:2}
          max-wait: ${REDIS.POOL.MAX_WAIT:3s}
        shutdown-timeout: ${REDIS.SHUTDOWN_TIMEOUT:100ms}

mybatis-plus:
  configuration:
    map-underscore-to-camel-case: true
    log-impl: org.apache.ibatis.logging.slf4j.Slf4jImpl
  global-config:
    db-config:
      id-type: auto

jwt:
  secret: ${JWT.SECRET:3MeKau+j794vsIX2jLgLaWYLAzd39ugtcNfNR5ScJX0=}
  access-token-expiration: ${JWT.AT.EXPIRE:10m}    # 10分钟
  refresh-token-expiration: ${JWT.RT.EXPIRE:7d} # 7天

storage:
  root-dir: ./storage
  avatar-dir: avatars
  access-path: /storage/

cache:
  multilevel:
    local-expire-after-write: 5m
    local-maximum-size: 1000
    redis-time-to-live: 30m
    redis-key-prefix: "sak:cache:"

logging:
  level:
    root: info
    com:
      sak:
        service:
          mapper: debug

notification:
  wxpusher:
    enabled: ${WXPUSHER.ENABLED:true}
    app-token: ${WXPUSHER.APP_TOKEN:AT_zltAvm2IsUP3H7zfr6LUoiUin8Hr0oBP}
    base-url: ${WXPUSHER.BASE_URL:https://wxpusher.zjiecode.com}
    content-type: ${WXPUSHER.CONTENT_TYPE:1}

ip2region:
  enabled: ${IP2REGION.ENABLED:true}
  ipv4-db: ${IP2REGION.IPV4_DB:./ip2region/ip2region_v4.xdb}
  ipv6-db: ${IP2REGION.IPV6_DB:}
  ipv4-classpath: ${IP2REGION.IPV4_CLASSPATH:}
  ipv6-classpath: ${IP2REGION.IPV6_CLASSPATH:}
